services:
  - type: web
    name: ummi-homestay
    env: static
    buildCommand: npm install
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
